README.md

The repo name changed. Also, first PR.

BAU: Change the H1 in the readme

---

.github/pull_request_template.md
CODEOWNERS
README.md

Add some basic setup of the repo.
- CODEOWNERS
- Pull request template
- README

PYI-444: Initial repo setup

---

.gitignore
terraform/lambda/api-gateway.tf
terraform/lambda/passport.tf
terraform/lambda/variables.tf
terraform/modules/endpoint/README.md
terraform/modules/endpoint/iam.tf
terraform/modules/endpoint/main.tf
terraform/modules/endpoint/outputs.tf
terraform/modules/endpoint/variables.tf

Add Terraform to create passport lamdba endpoint
Co-authored-by: @Wynndow 
- [PYI-443](https://govukverify.atlassian.net/browse/PYI-443)

PYI-446: Add Terraform to create passport lamdba endpoint

---

README.md

Remove merge conflict artefacts from README

BAU: Remove merge conflict artefacts from README

---

src/main/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandler.java

Ran `./gradlew :spotlessApply` to apply Spotless fixes. This sorted issuers with the imports in PassportHandler.

BAU: Fix Passport Handler spotless issue.

---

terraform/lambda/passport.tf

Correct the handler variable so that it points to the correct class.
The package name was not correct.

BAU: Correct Handler package

---

build.gradle

Update sonar config to ref the correct repo.
It was pointing to the wrong repo

BAU: Point Sonar at the correct repo

---

build.gradle
src/main/java/uk/gov/di/ipv/cri/passport/annotations/ExcludeFromGeneratedCoverageReport.java
src/main/java/uk/gov/di/ipv/cri/passport/domain/ProtectedHeader.java
src/main/java/uk/gov/di/ipv/cri/passport/domain/Thumbprints.java
src/main/java/uk/gov/di/ipv/cri/passport/exceptions/IpvCryptoException.java
src/main/java/uk/gov/di/ipv/cri/passport/service/ConfigurationService.java
src/main/java/uk/gov/di/ipv/cri/passport/service/DcsEncryptionService.java
src/main/java/uk/gov/di/ipv/cri/passport/service/DcsSigningService.java
src/test/java/uk/gov/di/ipv/cri/passport/service/ConfigurationServiceTest.java
src/test/java/uk/gov/di/ipv/cri/passport/service/DcsEncryptionServiceTest.java
src/test/java/uk/gov/di/ipv/cri/passport/service/DcsSigningServiceTest.java

- Added Signing Service to sign payload in a JWSObject
- Added Encryption Service to encrypt payload with DCS Encryption Certificate
To sign and encrypt payload before sending to DCS.
- [PYI-451](https://govukverify.atlassian.net/browse/PYI-451)

PYI-451: Add Signing Service and Encryption Service

---

terraform/lambda/parameter-store.tf
terraform/lambda/variables.tf

Changed "dcs_passport_url" to "dcs_post_url"
The variable being passed in from di-ipv-config is "dcs_post_url".
- [PYI-451](https://govukverify.atlassian.net/browse/PYI-451)

PYI-451: Change "passport" to "post"

---

build.gradle

We were getting warnings from gradle about a couple of issues. This
resolves them.
More details about spotless: https://github.com/diffplug/spotless/issues/1028
More details about reports: https://docs.gradle.org/7.3/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:enabled

BAU: Fix gradle warnings

---

build.gradle
src/main/java/uk/gov/di/ipv/cri/passport/lambda/StubDcsHandler.java
src/main/java/uk/gov/di/ipv/cri/passport/service/DcsCryptographyService.java
src/test/java/uk/gov/di/ipv/cri/passport/lambda/AccessTokenHandlerTest.java
src/test/java/uk/gov/di/ipv/cri/passport/lambda/DcsCredentialHandlerTest.java
src/test/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandlerTest.java
src/test/java/uk/gov/di/ipv/cri/passport/persistance/DataStoreTest.java
src/test/java/uk/gov/di/ipv/cri/passport/service/AccessTokenServiceTest.java
src/test/java/uk/gov/di/ipv/cri/passport/service/AuthorizationCodeServiceTest.java

We had quite a few places where conversions were unchecked. Gradle was
shouting at us about them. This fixes it.
To stop gradle being grumpy

BAU: Fix unchecked conversion warnings

---

deploy/samconfig.toml
deploy/template.yaml

Created `deploy/template.yaml` containing the sam definition to deploy this repository
Added `deploy/samconfig.toml` containing the deployment config for this repository
We're moving deployments of serverless technologies to SAM
- [PYI-587](https://govukverify.atlassian.net/browse/PYI-587)
- [SAM ADR]()

PYI-587 - Create SAM template

---

deploy/template.yaml

removed extra `"`
Invalid character for environment variable

BAU - Remove extra `"` breaking deployments

---

deploy/template.yaml

Add new resource to SAM template for new jwt-verification lambda function.
To deploy the new lambda with SAM.
- [PYI-PYI-592](https://govukverify.atlassian.net/browse/PYI-592)

PYI-592: Deploy new lambda with SAM template

---

deploy/template.yaml

Update name of lambda resource to follow same pattern of other resources
Match naming convention currently used

BAU: Update lambda to name to follow same pattern as other lambdas

---

deploy/template.yaml

Reverts alphagov/di-ipv-cri-uk-passport-back#55

Revert "BAU: Update lambda to name to follow same pattern as other lambdas"

---

terraform/lambda/parameter-store.tf

Update Client ID to match IPV Code Client ID.
- [PYI-631](https://govukverify.atlassian.net/browse/PYI-631)

PYI-631: Update Client ID to match IPV Code Client ID.

---

lambdas/accesstoken/build.gradle
lambdas/dcscredential/build.gradle
lambdas/jwtverification/build.gradle
lambdas/jwtverification/src/main/java/uk/gov/di/ipv/cri/passport/jwtverification/JwtVerificationHandler.java
lambdas/passport/build.gradle
lambdas/stubdcs/build.gradle
lib/build.gradle

Migrate JwtVerificationHandler to use slf4j to standardise on a single logging library. 
Also upgraded gradle packages and standardised on quotations in gradle build files.

BAU: Migrate JwtVerificationHandler to use slf4j to standardise on a single logging library. 

---

lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/PassportAttributesConverter.java

Fix to store forename as a String array in DynamoDB.
- [PYI-638](https://govukverify.atlassian.net/browse/PYI-638)

PYI-638: Fix to store forename as a String array in DynamoDB.

---

deploy/template.yaml

Increase lambda timeout to be 40 seconds
We are currently reaching the 20 second limit due to cold starts.
- [PYI-639](https://govukverify.atlassian.net/browse/PYI-639)

PYI-639: Increase timeout of passport lambdas

---

lambdas/dcscredential/src/main/java/uk/gov/di/ipv/cri/passport/dcscredential/DcsCredentialHandler.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/PassportAttributesConverter.java

Fix unused imports and fields that cause code smells in Sonar Report.

BAU: Fix code smells.

---

deploy/template.yaml

Added an output for the stack containing the API Gateway ID
We'll need to reference this output in the parameters stack
- [PYI-694](https://govukverify.atlassian.net/browse/PYI-694)

PYI-694 - Added output for gateway id

---

integration-test/src/integration-test/java/uk/gov/di/ipv/cri/passport/integrationtest/DateStorePassportCheckIT.java
lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandlerTest.java
lambdas/jwtverification/src/test/java/uk/gov/di/ipv/cri/passport/jwtverification/JwtVerificationHandlerTest.java
lambdas/passport/src/test/java/uk/gov/di/ipv/cri/passport/passport/PassportHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/DcsResponse.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
lib/src/test/java/uk/gov/di/ipv/cri/passport/library/helpers/RequestHelperTest.java
lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/AuthorizationCodeServiceTest.java
lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/DcsCredentialServiceTest.java
lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/DcsCryptographyServiceTest.java
lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/PassportServiceTest.java

Cleaned up unused variables or constants within tests.
Used lambdas instead of function calls.
Implemented code style and performance suggestions.

BAU: Cleaned up unused variables or constants within tests.

---

lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandler.java
lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandlerTest.java
lambdas/passport/src/main/java/uk/gov/di/ipv/cri/passport/passport/PassportHandler.java
lambdas/passport/src/test/java/uk/gov/di/ipv/cri/passport/passport/PassportHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/AuthorizationCodeItem.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/AuthorizationCodeService.java
lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/AuthorizationCodeServiceTest.java

Validate that the redirect url is still valid for the /token request.
- Persist the redirect url with the auth code
- Check then redirect url within the /token request params matches with what is stored against the auth code
Ensures that the redirect url is valid on both auth and token requests/
- [PYI-697](https://govukverify.atlassian.net/browse/PYI-697)

PYI-697: Validate that the redirect url has not changed since the previous url during the auth request

---

deploy/template.yaml
lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandler.java
lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/domain/ConfigurationServicePublicKeySelector.java
lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/exceptions/ClientAuthenticationException.java
lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/validation/TokenRequestValidator.java
lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandlerTest.java
lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/validation/TokenRequestValidatorTest.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java

Authenticate client with client_assertion jwt in incoming /token request.
Client authentication is required for incoming /token requests based off which clients we have configured.
- [PYI-715](https://govukverify.atlassian.net/browse/PYI-715)

PYI-715: Authenticate client with client_assertion jwt

---

deploy/template.yaml

Add environment variables to correct Lambda to resolve null pointer exception on Issue Credential Handler.

FIX: Add environment variables to correct Lambda to resolve null pointer exception on Issue Credential Handler.

---

deploy/template.yaml

The issue credential lambda didn't have perms to fetch the signing key
ID from the param store.

BAU: Fix parameter store perms for issue credential lambda

---

deploy/template.yaml

The issue credential lambda needs a couple more perms

BAU: Fix missing param store perms

---

lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java

Adds extra logging and separates some errors to help diagnose issues
with signing the VC.

BAU: Extra logging and catch block

---

deploy/template.yaml

Without this the lambda can't use the KMS key to sign VCs.

BAU: Give issue credential lambda perms to sign

---

lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/domain/ConfigurationServicePublicKeySelectorTest.java
lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/validation/TokenRequestValidatorTest.java
lambdas/issuecredential/build.gradle
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/error/ErrorResponse.java
lib/src/test/java/uk/gov/di/ipv/cri/passport/library/lambda/OAuth2RequestParams.java

Refactoring a cleanups:
- Refactor Test Certificates and Keys to use TestFixtures
- Removed unused logger
- Replace Lambdas in Tests
- Remove unused OAuth Params

BAU: Refactor Test Certificates and Keys to use TestFixtures

---

lambdas/sharedattributes/src/main/java/uk/gov/di/ipv/cri/passport/sharedattributes/SharedAttributesHandler.java
lambdas/sharedattributes/src/test/java/uk/gov/di/ipv/cri/passport/sharedattributes/SharedAttributesHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/error/ErrorResponse.java

Move shared attributes up a level and rename to shared_claims as root claim object.

PYIC-888: Move shared attributes up a level and rename to shared_claims as root claim object.

---

lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/VerifiableCredential.java
lib/src/test/java/uk/gov/di/ipv/cri/passport/library/helpers/JwtHelperTest.java

Updated the evidence to be stored as a list.
Matches with the cri stubs and the current spec.

Update evidence to be stored as a list

---

lambdas/sharedattributes/src/main/java/uk/gov/di/ipv/cri/passport/sharedattributes/SharedAttributesHandler.java

Log details of the nimbus error object within the JarValidationException

BAU: improve error log

---

deploy/template.yaml

Add missing env var for the max ttl SSM param name

BAU: Add env var for the max ttl ssm param

---

lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java

Set the subject claims of the returned VC JWT, to be the userId value that came from the subject of the JAR.
The subject of the JAR claim has already been stored within the DcsResponse table during the authorise request, so this value is now available when we read this out of the dynamoDb table when generating the VC.
To match the expected spec of the VC where the subject claim should be the same for the connecting JAR and the returned VC out of a CRI.
- [PYI-966](https://govukverify.atlassian.net/browse/PYI-966)

PYIC-966: Set the subject of the returned VC JWT as the subject from the JAR

---

.github/workflows/post-merge.yml

Fix indentation error in yaml file.

Fix github-actions post merge indentation error

---

deploy/template.yaml

Give credential issuer lambda perms
We need to give the lambda permission to get the clients config, as well
as set the env var for the config service to construct the param name.
- [PYI-1238](https://govukverify.atlassian.net/browse/PYI-1238)

PYIC-1238: Give credential issuer lambda perms

---

deploy/template.yaml

PYIC-1248
Created API Keys for external passport core back.
- [PYI-1248](https://govukverify.atlassian.net/browse/PYI-1248)

PYIC-1248-cri-passport-back-api-keys

---

deploy/template.yaml

This enables Passport back api gateway api key enforcement
This enforces api keys required for api gateways. 
- [PYIC-1249](https://govukverify.atlassian.net/browse/PYIC-1249)

PYIC-1249 This enables Passport back api gateway api key enforcement

---

.github/workflows/checkov.yml

Checkov is a static analysis tool for infrastructure-as-code. It will
spot common mistakes and flaws in our CFN template. For now it will run
when the core-back template changes but should not fail the PR build.
Rolling out to all IPV and Passport CFN templates.
- [PYI-1073](https://govukverify.atlassian.net/browse/PYI-1073)

PYIC-1073 Run Checkov on PRs

---

deploy/template.yaml

Changed the arch to arm64
This was requested.
- [PYIC-407](https://govukverify.atlassian.net/browse/PYIC-407)

PYIC-407 changed lambda arch to arm64

---

deploy/template.yaml

Add audit queue KMS permission for JwtAuthorizationRequest handler
To fix KMS permission error for this lambda
Follow-up to [PYIC-1088](https://govukverify.atlassian.net/browse/PYIC-1088)

PYIC-1088 Add audit queue KMS permission for JwtAuthorizationRequest handler

---

deploy/template.yaml

Added private api gateway to passport back4
Make Passport Back Internal API Private
- [PYI-1304](https://govukverify.atlassian.net/browse/PYI-1304)

PYIC-1304 aded private api gateway to passport back

---

deploy/template.yaml

Removed internal api after replacing it with private api
Make Passport Back Internal API Private

PYIC-1307 removed internal api

---

.pre-commit-config.yaml

This adds pre-commit configuration file for configuring pre-commit git hooks (this requires the installation of pre-commit)
This adds pre-commit configuration file for configuring pre-commit git hooks (this requires the installation of pre-commit)
This is added so we can make sure cloud formation files are linted and other basics are checked.
- [PYIC-1399](https://govukverify.atlassian.net/browse/PYIC-1399)

PYIC-1399 Added pre-commit config

---

.pre-commit-config.yaml
README.md

This updates the documentation and includes notes on how to use / install the pre-commit hooks. 
Documentation was requested for usage. 
- [PYIC-1399](https://govukverify.atlassian.net/browse/PYIC-1399)

PYIC-1399 updated Readme

---

.github/workflows/checkov.yml
deploy/template.yaml

Added checkov fixes
To enable Checkov on the pipeline

PYIC-1293 added checkov fixes

---

.github/workflows/post-merge.yml

The git commit will be used to tag the stack when it is deployed via
Concourse.
As above
Following pattern as per core-back
To make it simpler to see which commit is deployed in each environment.
- [PYI-1501](https://govukverify.atlassian.net/browse/PYI-1501)

PYIC-1501 Add Git Commit to Zip archive

---

lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/AccessTokenService.java

Update default scope value ot macth with what we use on core.

Update the default scope value to match with core

---

deploy/template.yaml

Fix indentation

---

lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java

Conditionally use resource ID from session
The issuecredential lambda should check to see if the token enty it is
using contains a dcs resource id. If it does, it should be used to to
generate the VC. If not, the session id should be used to open the
session object and use the dcs resource id from there, genearting the VC
as normal.
- [PYI-1555](https://govukverify.atlassian.net/browse/PYI-1555)

PYIC-1555: Conditionally use resource ID from session

---

deploy/template.yaml

Add aws SAM config for the new build-client-oauth-response lambda.
To deploy new lambda to aws with the required DB permissions
- [PYI-1552](https://govukverify.atlassian.net/browse/PYI-1552)

PYIC-1552: Add SAM config for the new build-client-oauth-response lambda

---

deploy/samconfig.toml
deploy/template.yaml

Update allowed environment list to allow all new passport dev environments. 
Also added environment name to the external api name

BAU: Add new envs to allowed list and setup EnvironmentConfiguration

---

build.gradle
deploy/samconfig.toml
integration-test/build.gradle
lambdas/accesstoken/build.gradle
lambdas/buildclientoauthresponse/build.gradle
lambdas/checkpassport/build.gradle
lambdas/initialisesession/build.gradle
lambdas/issuecredential/build.gradle

- Remove application plugin to stop duplicate JARs and allow sam to build in parallel.

BAU: Remove application plugin to stop duplicate JARs and allow sam to build in parallel.

---

.sdkmanrc

Add .sdkmanrc file.
We use SDKMAN to manage java versions. Adding the .sdkmanrc file enables setting the java version locally automatically.

BAU: Add SDKMAN .sdkmanrc

---

deploy/template.yaml

PYIC-1733 Passport Back renamed api gateway id to PassportBackAPIGatewayID-${Environment}
PYIC-1733 Passport Back renamed api gateway id to PassportBackAPIGatewayID-${Environment}
This should only effect the DNS stack and have no knock on effects for the dev environment - as dev has no dns.
This is necessary as stack name will not always contain the actual environment name,
- [PYIC-1733](https://govukverify.atlassian.net/browse/PYIC-1733)

PYIC-1733 Passport Back renamed api gateway id to PassportBackAPIGatewayID-${Environment}

---

.github/workflows/concourse-post-merge.yml
.github/workflows/secure-post-merge.yml

PYIC-1715 fixed secure pipeline issues - added concourse to name of concourse pipeline
PYIC-1715 fixed secure pipeline issues - added concourse to name of concourse pipeline

PYIC-1715 fixed secure pipeline issues - added concourse to name of concourse pipeline

---

.github/workflows/concourse-post-merge.yml
.github/workflows/secure-post-merge.yml

PYIC-1715 fixed names for pipelines
PYIC-1715 fixed names for pipelines

PYIC-1715 fixed names for pipelines

---

.github/workflows/secure-post-merge.yml

PYIC-1715 Switched to di-devplatform-upload-action
PYIC-1715 Switched to di-devplatform-upload-action
This injects metadata with the upload - without this the infrastructure audit hook fails. 

PYIC-1715 Switched to di-devplatform-upload-action

---

.github/workflows/concourse-post-merge.yml

PYIC-1715 Added Lambda signing to concourse pipeline
PYIC-1715 Added Lambda signing to concourse pipeline 
Concourse pipeline will break now once the lambda pipelines have been deployed and signed - this adds the signature for concourse. 

PYIC-1715 Added Lambda signing to concourse pipeline

---

.github/workflows/concourse-post-merge.yml

PYIC-1715 Cleaned up concourse pipeline naming
PYIC-1715 Cleaned up concourse pipeline naming
purely cosmetic changes

PYIC-1715 Cleaned up concourse pipeline naming

---

infrastructure/lambda/template.yaml

LIME-131 Github actions check.

---

.github/workflows/pre-merge-checks.yml
.github/workflows/secure-post-merge.yml
infrastructure/lambda/template.yaml

LIME-131 Update DCS_RESPONSE_TABLE_NAME in workflows.

---

.github/workflows/secure-post-merge.yml

LIME-131 Update workflows.

---

.github/workflows/secure-post-merge.yml

LIME-131 Update workflows (gradle buildZip)

---

infrastructure/lambda/template.yaml

Added PermissionsBoundary to globals section of template.
PermissionsBoundary where enabled after template was converted and missed. 

Add PermissionsBoundary to globals.

---

deploy/template.yaml

Re-enabling api-gateway log group creation.
Log group creation was disabled temporarily in previous commit.

LIME-131 Re-enable APIGateway log group creation.

---

deploy/template.yaml

Add new SubscriptionFilter destinations 
To provide seamless transition when old destinations are turned off
- [LIME-192](https://govukverify.atlassian.net/browse/LIME-192)

LIME-192 Add new SubscriptionFilter destinations.

---

deploy/template.yaml

Reverts alphagov/di-ipv-cri-uk-passport-back#241

Revert "LIME-192 Keep current names for old subscription filter and add CSLS to new"

---

deploy/template.yaml

Fixing a typo in the CSLS destination filter.

LIME-192 Update CSLS destination to correct value.

---

build.gradle
integration-test/build.gradle
lambdas/accesstoken/build.gradle
lambdas/buildclientoauthresponse/build.gradle
lambdas/checkpassport/build.gradle
lambdas/initialisesession/build.gradle
lambdas/issuecredential/build.gradle
lib/build.gradle

Updated passport to use common lib
To allow passport to utilise shared cri code

Lime 130: Adding common lib to passport

---

deploy/template.yaml

Fixed yaml formatting
To allow promotion to build

LIME-243: Fixed yaml formatting issues

---

deploy/template.yaml

Added new alert to monitor lambda invocations on session and issue credential
To inform us of any significant deviation between people starting the journey and people completing the journey within the CRI

LIME-384: Adding alert to notify if ther is a deviation between users starting the CRI and users completing it

---

lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/ConfigurationService.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/ConfigurationVariable.java
lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationServiceTest.java

Added additional logging on what config variables are being used
Updated config variable names to avoid any issues with parameter history
To fix an issue in production related to using old parameters after an update

Certificate rotation logging

---

lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/ConfigurationService.java

Updated hash logging method
So that were logging config var paths not variable names

certificate-rotation-logging: Fixed issue were incorrect values are logged

---

.github/workflows/pre-merge-checks.yml
.github/workflows/secure-post-merge.yml

Pinned gradle version 7.6
Codebase supports gradle version 7.6

LIME-529-2 - Updated gradle version from 7.3 to 7.6

---

deploy/template.yaml
lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/ConfigurationService.java
lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/ConfigurationVariable.java

Added code to remove the VC expiry dependant on environment
To allow the testing and eventual removal of VC expiry's in CRIs

LIME-567: Removed expiry from VC based on release flag

---

.github/workflows/secure-post-merge.yml

Added workflow dispatch to package for build job
So that we can manually check deployment pipelines

Adding workflow dispatch so passport pipelines can be manually tested

---

.github/workflows/secure-post-merge.yml

Added steps to push tests to amazon from post merge action
To renable testing following the control tower migration

LIME-603: Re-introducing the testing stage based on local tests

---

acceptance-tests/src/test/resources/features/passport/WelshLangPassport.feature

Updated tests to reflect the translation changes in the FE PR
https://github.com/alphagov/di-ipv-cri-uk-passport-front/pull/543

LIME-668 Updating welsh translation tests
