- src/main/java/uk/gov/di/ipv/cri/passport/helpers/ApiGatewayResponseGenerator.java
- src/main/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandler.java
Move classes so that they are in packages starting `uk.gov.di.ipv`
We should keep a consistent package space across our project. They should all start `uk.gov.di.ipv`
> BAU: Move to correct packages

- build.gradle
- src/main/java/uk/gov/di/ipv/cri/passport/dto/DcsCheckRequestDto.java
- src/main/java/uk/gov/di/ipv/cri/passport/error/ErrorResponse.java
- src/main/java/uk/gov/di/ipv/cri/passport/helpers/ApiGatewayResponseGenerator.java
- src/main/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandler.java
- src/test/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandlerTest.java
This adds logic to the passport handler to receive the passport details
in the body of the request and convert them to a DTO.
We do some light validation on the DTO to give us confidence that we're
not getting junk from the frontend.
- [PYI-438](https://govukverify.atlassian.net/browse/PYI-438)
> PYI-438: Handle passport form data from frontend

- src/main/java/uk/gov/di/ipv/cri/passport/dto/DcsCheckRequestDto.java
- src/test/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandlerTest.java
Remove timestamp requirement of the passport date fields.
Remove public class modifier in test that is recognised as a code smell within sonar.
DCS service expects the dates in the format YYYY-MM-DD so the timestamp is not required, and the front-end does not provide any time values.
- [PYI-459](https://govukverify.atlassian.net/browse/PYI-459)
> PYI-459: Remove timestamp from passport date fields 

- src/main/java/uk/gov/di/ipv/cri/passport/dto/DcsCheckRequestDto.java
to fix missing fields when using the… ObjectMapper to create json string
Add @JsonProperty annotation to the dto fields.
To fix the issue that these fields are currently skipped when using the ObjectMapper to write the object as a JSON string.
> BAU: Add missing JsonProperty annotation 

- terraform/lambda/kms.tf
- terraform/lambda/parameter-store.tf
- terraform/lambda/passport.tf
- terraform/modules/endpoint/main.tf
- terraform/modules/endpoint/outputs.tf
- terraform/modules/endpoint/variables.tf
Some terraform to create signing and encryption asymmetric key pairs for
use by the passport CRI with DCS. It provides the key IDs to the lambda as
env variables.
We've decided to hold fire on using KMS for a TLS key until we've
learnt a bit more.
It also changes the way we provide the env vars to the lambda, passing
a map into the module rather than declaring the variables.
- [PYI-465](https://govukverify.atlassian.net/browse/PYI-465)
> PYI-465: Generate KMS keys for use with DCS

- terraform/lambda/kms.tf
- terraform/lambda/parameter-store.tf
- terraform/lambda/passport.tf
- terraform/lambda/variables.tf
**See the accompanying PR here: https://github.com/alphagov/di-ipv-config/pull/70**
The previous approach of using dummy data for the parameter values which
we'll update outside of terraform won't work. Terraform will just try to
overwrite it the next time it's applied. Setting the `overwrite` flag to
false didn't do what I'd expected it to. Instead it just throws an
error.
This change uses values for the certs passed in from the terraform
project root in `di-ipv-config` for the non-secure parameters. We'll
need to manage the "SecureString" parameters completely outside of
Terraform as we can't pass the secret values in in the same way.
- [PYI-465](https://govukverify.atlassian.net/browse/PYI-465)
> PYI-465: Give parameters real values

- README.md
- terraform/lambda/dynamodb.tf
- terraform/lambda/passport.tf
- terraform/modules/endpoint/iam.tf
- terraform/modules/endpoint/variables.tf
Add terraform resources for dynamoDB tables:
- cri-passport-auth-codes
- cri-passport-access-tokens
- cri-passport-credentials
To create the required aws DynamoDB resources for storing auth-codes/access-tokens/credentials
- [PYI-470](https://govukverify.atlassian.net/browse/PYI-470)
> PYI-470: Add terraform resources for auth-codes, access-tokens and protected resources dynamodb tables

- build.gradle
- src/main/java/uk/gov/di/ipv/cri/passport/persistence/DataStore.java
- src/main/java/uk/gov/di/ipv/cri/passport/persistence/item/AuthorizationCodeItem.java
- src/test/java/uk/gov/di/ipv/cri/passport/persistance/DataStoreTest.java
Created new DataStore class to handle the read/write/delete to DynamoDB.
Created AuthorisationCodeItem class.
The class will be used to handle all read/write/deletes to the DB for authcodes, access tokens and DCS resources.
- [PYI-471](https://govukverify.atlassian.net/browse/PYI-471)
> PYI-471: Create DataStore class to read/write/delete to DynamoDB

- src/main/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandler.java
- src/main/java/uk/gov/di/ipv/cri/passport/persistence/item/DcsResponseItem.java
- src/main/java/uk/gov/di/ipv/cri/passport/service/ConfigurationService.java
- src/main/java/uk/gov/di/ipv/cri/passport/service/PassportService.java
- src/test/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandlerTest.java
- src/test/java/uk/gov/di/ipv/cri/passport/service/PassportServiceTest.java
- terraform/lambda/dynamodb.tf
- terraform/lambda/passport.tf
- terraform/modules/endpoint/iam.tf
- terraform/modules/endpoint/variables.tf
- Created new DynamoDB DcsResponseItem class.
- Add new persistence method in the passportService to store the dcs response in the DB.
- Refactor the terraform dcs-response table names and env variables.
Need to store the response from DCS into dynamo that can then be later retrieved with an access token.
- [PYI-472](https://govukverify.atlassian.net/browse/PYI-472)
> PYI-472: Persist the dcs response into the dcs-response DynamoDB table

- src/main/java/uk/gov/di/ipv/cri/passport/annotations/ExcludeFromGeneratedCoverageReport.java
- src/main/java/uk/gov/di/ipv/cri/passport/domain/DcsResponse.java
- src/main/java/uk/gov/di/ipv/cri/passport/lambda/StubDcsHandler.java
- src/main/java/uk/gov/di/ipv/cri/passport/service/ConfigurationService.java
- terraform/lambda/parameter-store.tf
- terraform/lambda/stub-dcs.tf
- terraform/lambda/variables.tf
**See the companion PR that invokes this new terraform here: https://github.com/alphagov/di-ipv-local-startup/pull/18**
This adds a lambda that will only be deployed locally. It's a stub for
DCS.
Currently it ignores the incoming payload and generates a valid response
with new UUIDs.
When we've finished the work in the passport CRI to verify and decrypt
response from the DCS, we can steal the logic to unwrap incoming
payloads to the stub DCS and use the UUIDs contained in the response.
It will use dev PKI that is passed in from the terraform project root in
local-startup. It goes without saying that this PKI should never be used
for anything else.
- [PYI-476](https://govukverify.atlassian.net/browse/PYI-476)
> PYI-476: Add stub DCS lambda

- src/main/java/uk/gov/di/ipv/cri/passport/error/ErrorResponse.java
- src/main/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandler.java
- src/main/java/uk/gov/di/ipv/cri/passport/persistence/item/AuthorizationCodeItem.java
- src/main/java/uk/gov/di/ipv/cri/passport/service/AuthorizationCodeService.java
- src/main/java/uk/gov/di/ipv/cri/passport/service/ConfigurationService.java
- src/main/java/uk/gov/di/ipv/cri/passport/service/PassportService.java
- src/main/java/uk/gov/di/ipv/cri/passport/validation/ValidationResult.java
- src/test/java/uk/gov/di/ipv/cri/passport/lambda/OAuth2RequestParams.java
- src/test/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandlerTest.java
- src/test/java/uk/gov/di/ipv/cri/passport/persistance/DataStoreTest.java
- src/test/java/uk/gov/di/ipv/cri/passport/service/AuthorizationCodeServiceTest.java
- terraform/lambda/passport.tf
- Read and validate the required oauth query parameters from incoming request into lambda.
- Generate an authorisation code and store it within DynamoDB linked to the DCS resource via resourceId field.
- Return the auth-code back to cri-passport-front.
Auth code will be needed for the cri-passport oauth flow in order to control access to the protected resource.
- [PYI-462](https://govukverify.atlassian.net/browse/PYI-462)
> PYI-462: Generate and return an oauth auth-code on passport validation request

- src/main/java/uk/gov/di/ipv/cri/passport/lambda/DcsCredentialHandler.java
- terraform/lambda/dcs-credential.tf
Add new terraform file to create a new empty lamdba for the dcs credential and wire it up with the aws api gateway.
This is the terraform infrastructure required to deploy this new lambda needed for the cri-passport oauth flow.
- [PYI-481](https://govukverify.atlassian.net/browse/PYI-481)
> PYI-481: Minimal lambda and terraform to setup aws gateway and empty lambda

- src/main/java/uk/gov/di/ipv/cri/passport/domain/DcsPayload.java
- src/main/java/uk/gov/di/ipv/cri/passport/exceptions/StubDcsException.java
- src/main/java/uk/gov/di/ipv/cri/passport/lambda/StubDcsHandler.java
- src/main/java/uk/gov/di/ipv/cri/passport/serialization/LocalDateDeserializer.java
- src/main/java/uk/gov/di/ipv/cri/passport/service/ConfigurationService.java
- terraform/lambda/parameter-store.tf
- terraform/lambda/passport.tf
- terraform/lambda/stub-dcs.tf
- terraform/lambda/variables.tf
**See the companion PR here: https://github.com/alphagov/di-ipv-local-startup/pull/23**
**Also this one: https://github.com/alphagov/di-ipv-config/pull/81**
This adds verification and decryption of the incoming payload from the
Passport CRI in the stub DCS. We then return a response to the CRI using
the correlation and request IDs contained in the original request.
This will help give us confidence that the request we're sending to DCS
is legit.
- [PYI-476](https://govukverify.atlassian.net/browse/PYI-476)
> PYI-476: Verify/decrypt payload in stub DCS

- build.gradle
- src/integration-test/java/uk/gov/di/ipv/cri/passport/integrationtest/HelloIntegrationTest.java
Added a new source set and task for running integration tests.
We want to be able to run our integration tests independently of our
unit tests. This is so we don’t have to set up a convoluted environment
when running the unit tests. Further work to be done to actually set up
that environment.
> PYI-492: Set up new source set for integration tests

- terraform/lambda/dcs-credential.tf
Add missing dynamoDB table name for the dcs-response lambda and remove unused table name var.
> BAU: Fix missing env var for dcs-response table name

- terraform/lambda/parameter-store.tf
- terraform/modules/endpoint/iam.tf
Add dcs_post_url param to the parametere store policy resource list.
Currently the passport lambda fails to read this parameter from SSM due to the missing policy permission, and it requires this param in order to send a POST request out to the DCS validate api endpoint.
> Bau fix missing policy permission

- src/main/java/uk/gov/di/ipv/cri/passport/helpers/ApiGatewayResponseGenerator.java
- src/main/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandler.java
- src/main/java/uk/gov/di/ipv/cri/passport/lambda/StubDcsHandler.java
- src/main/java/uk/gov/di/ipv/cri/passport/service/PassportService.java
- src/test/java/uk/gov/di/ipv/cri/passport/service/PassportServiceTest.java
- terraform/lambda/passport.tf
Check the response from DCS and if the status code is not 200 then log
the status code and return an error to passport frontend. Note that the
response entity isn't being logged with the error just in case it contains
something sensitive.
Check the response from DCS and if the status code is not 200 then log
the status code and return an error to passport frontend. Note that the
response entity isn't being logged with the error just in case it contains
something sensitive.
Guidance on DCS passport validity check is available here showing the status code should be 200 for a successful check: https://dcs-pilot-docs.cloudapps.digital/api-reference/#interpret-the-passport-validity-response
Previously we were attempting to parse non-200 responses into a JWS which threw a confusing error.
> PYI-452 Handle non 200 response from DCS

- src/integration-test/java/uk/gov/di/ipv/cri/passport/integrationtest/DataStoreIT.java
- src/main/java/uk/gov/di/ipv/cri/passport/domain/DcsResponse.java
- src/main/java/uk/gov/di/ipv/cri/passport/domain/PassportFormRequest.java
- src/main/java/uk/gov/di/ipv/cri/passport/error/ErrorResponse.java
- src/main/java/uk/gov/di/ipv/cri/passport/helpers/ApiGatewayResponseGenerator.java
- src/main/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandler.java
- src/main/java/uk/gov/di/ipv/cri/passport/persistence/item/DcsResponseTypeConverter.java
- src/main/java/uk/gov/di/ipv/cri/passport/service/ConfigurationService.java
- src/main/java/uk/gov/di/ipv/cri/passport/service/PassportService.java
- src/test/java/uk/gov/di/ipv/cri/passport/lambda/PassportHandlerTest.java
- src/test/java/uk/gov/di/ipv/cri/passport/service/DcsCryptographyServiceTest.java
- Fix error handling for the DCS response so that when DCS returns an error we log that error and return a 500 error response.
- Fix the DCSPayload timestamp field date format to follow what DCS expects.
Improve our handling of the possible DCS responses and fix the DCS verification of our passport validation requests.
- [PYI-452](https://govukverify.atlassian.net/browse/PYI-452)
> Pyi 452/fix error handling

- deploy/template.yaml
- terraform/lambda/parameter-store.tf
- terraform/lambda/variables.tf
setting up  the config variables that are used to pull certificates from SSM . These variables will be used in Configuration 
service ultimately
- [PYI-619](https://govukverify.atlassian.net/browse/PYI-619)
> PYI 619 add config to contain signature verification cert in SSM

- terraform/lambda/parameter-store.tf
- terraform/lambda/variables.tf
The signing cert for verifying the shared attributes JWS has been added
to the config repo. See here: https://github.com/alphagov/di-ipv-config/pull/121 
We need to add this variable here to stop the terraform
from breaking.
This sets the cert as a parameter in the parameter store. The name of
the parameter may need changing now we're managing config in a
structured way.
- [PYI-612](https://govukverify.atlassian.net/browse/PYI-612)
> PYI-612: Add shared attributes signing cert var

- terraform/lambda/parameter-store.tf
- terraform/lambda/variables.tf
This should have been added to the core-back, not passport-back.
See it being added to the correct place here: https://github.com/alphagov/di-ipv-core-back/pull/112
- [PYI-612](https://govukverify.atlassian.net/browse/PYI-612)
> Revert "PYI-612: Add shared attributes signing cert var"

- lambdas/dcscredential/src/main/java/uk/gov/di/ipv/cri/passport/dcscredential/DcsCredentialHandler.java
- lambdas/dcscredential/src/main/java/uk/gov/di/ipv/cri/passport/dcscredential/domain/PassportCredentialIssuerResponse.java
- lambdas/dcscredential/src/test/java/uk/gov/di/ipv/cri/passport/dcscredential/DcsCredentialHandlerTest.java
- lambdas/dcscredential/src/test/java/uk/gov/di/ipv/cri/passport/dcscredential/domain/PassportCredentialIssuerResponseTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/PassportAttributesConverter.java
Update DcsCredentialHandler to return PassportCredentialIssuerResponse that maps the DcsResponse to core's expected Credential format.
- [PYI-638](https://govukverify.atlassian.net/browse/PYI-638)
> PYI-638: Update DcsCredentialHandler to return PassportCredentialIssuerResponse

- deploy/template.yaml
- lambdas/jwtverification/src/main/java/uk/gov/di/ipv/cri/passport/jwtverification/JwtVerificationHandler.java
- lambdas/jwtverification/src/test/java/uk/gov/di/ipv/cri/passport/jwtverification/JwtVerificationHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
**Companion PR doing the restructure: https://github.com/alphagov/di-ipv-config/pull/130**
The structure of the config in the parameter store has changed. This
updates the deploy template to reflect this. It also makes a small
change to the ConfigurationService code.
It also removes the deploy of the stub-dcs lambda. This lambda was only
ever supposed to be deployed locally. In the dev environment we can talk
to the integration DCS directly.
If we get a local running solution in the future we can resurrect it, so
i'm leaving the stub DCS code where it is for now.
- [PYI-641](https://govukverify.atlassian.net/browse/PYI-641)
> PYI-641: Use new configuration structure

- lambdas/dcscredential/src/main/java/uk/gov/di/ipv/cri/passport/dcscredential/domain/Name.java
- lambdas/dcscredential/src/main/java/uk/gov/di/ipv/cri/passport/dcscredential/domain/PassportCredentialIssuerResponse.java
- lambdas/dcscredential/src/test/java/uk/gov/di/ipv/cri/passport/dcscredential/DcsCredentialHandlerTest.java
- lambdas/dcscredential/src/test/java/uk/gov/di/ipv/cri/passport/dcscredential/domain/PassportCredentialIssuerResponseTest.java
Update PassportCredentialIssuerResponse object to now store all of the 'familyName' and 'givenNames' properties within a 'names' object.
To match our expected data structure from core-back and to fix the shared attributes requests.
- [PYI-654](https://govukverify.atlassian.net/browse/PYI-654)
> PYI-654: Update structure of the PassportCredentialIssuerResponse to match expected data structure

- deploy/template.yaml
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
This adds a missing slash at the beginning of the param.
It also removes the trailing slash to avoid an issue found with getting
multiple values using the prefix. This was not an issue here but it's
good to be consistant.
> BAU: Fix slash for cred issuer config param

- lambdas/passport/src/main/java/uk/gov/di/ipv/cri/passport/passport/PassportHandler.java
- lambdas/passport/src/test/java/uk/gov/di/ipv/cri/passport/passport/PassportHandlerTest.java
Updated the max validity score to be 2.
For the passport gpg45 score the evidence strength should be 4, and the validity is either 0 or 2 depending on the result of the DCS response.
- [PYI-656](https://govukverify.atlassian.net/browse/PYI-656)
> PYI-656: Update gpg45 score values

- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/exceptions/HttpResponseExceptionWithErrorBody.java
Better that the `HttpResponseExceptionWithErrorBody` custom exception
extends Exception rather than Throwable to follow convention.
> BAU Extend Exception rather than Throwable

- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/exceptions/HttpClientException.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/helpers/HttpClientSetUp.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
[3649af2](https://github.com/alphagov/di-ipv-cri-uk-passport-back/pull/86/commits/3649af2f019ddf9b63bfb0107ae79b8ac8d097db)
The ssmProvider will throw a ParameterNotFound runtime exception rather
than returning null, so the use of the optional is unnecessary.
[13cb14b](https://github.com/alphagov/di-ipv-cri-uk-passport-back/pull/86/commits/13cb14b5864f9fc5637eba0bf175238eb17a9486)
* Throw custom exception in http client setup. We shouldn't be throwing generic exceptions like RuntimeExceptions.
* Use format specifiers instead of string concatenation
* Refactor env string to constant
> BAU: Remove Optional from config service and fix code smells

- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
Updated name of SSM param for the passport public cert used for signature verification to match the value in config.
> BAU: Fix ssm path name for passport cri public cert name

- deploy/template.yaml
Grant the DCS auth lambda permission to access the necessary SSM Parameters.
- [PYI-726](https://govukverify.atlassian.net/browse/PYI-726)
> PYI-726 Correct SSM Permissions for DCS Auth Lambda

- deploy/template.yaml
Add the `!Sub` function to interpolate the environment parameter into
the strings.
Co-authored-by Daniel Hayes <daniel.hayes@digital.cabinet-office.gov.uk>
- [PYI-726](https://govukverify.atlassian.net/browse/PYI-726)
> PYI-726 Correct SAM Template for DCS Token Lambda

- lambdas/jwtverification/src/main/java/uk/gov/di/ipv/cri/passport/jwtverification/JwtVerificationHandler.java
- lambdas/jwtverification/src/test/java/uk/gov/di/ipv/cri/passport/jwtverification/JwtVerificationHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/error/ErrorResponse.java
Expect sharedAttribute values in vc_http_api claim
In [RFC 0008](https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0008-identity-ipv-sequence-diagram.md#authorize)
we stipulate that the shared attributes will be encapsulated in a top
level claim in the JWT called vc_http_api.
The KBV team has implemented this, and we should probably do the same
thing.
core-back has been updated to use this top level claim in [PR 154](https://github.com/alphagov/di-ipv-core-back/pull/154)
> BAU: Expect sharedAttribute values in vc_http_api claim

- lambdas/jwtverification/src/main/java/uk/gov/di/ipv/cri/passport/jwtverification/JwtVerificationHandler.java
- lambdas/jwtverification/src/test/java/uk/gov/di/ipv/cri/passport/jwtverification/JwtVerificationHandlerTest.java
**Companion PR on core-back here: https://github.com/alphagov/di-ipv-core-back/pull/155**
RFC 0008 actually specifies that the custom vc_http_api claim should be
nested under a top level claim in the JWT called `claims`.
This is to keep in line with the OIDC spec which we're sort of following.
https://openid.net/specs/openid-connect-core-1_0.html#RequestObject
To meet the spec we've laid out.
> BAU: Expect vc_http_api claim in a claims claim

- .github/workflows/post-merge.yml
To build and package the sam artifacts and stick them in S3. Uses all
the same patterns as the existing workflow in core-back
- [PYI-138](https://govukverify.atlassian.net/browse/PYI-138)
> PYIC-138: Add post merge github action

- deploy/template.yaml
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
**PR to create the values being referenced here in the param store: https://github.com/alphagov/di-ipv-config/pull/269**
We need to provide a value for the issuer when generating VCs. This
should come from config. It must be a URL. Initially we’ll set it to the
host of the passport CRI.
- [PYI-861](https://govukverify.atlassian.net/browse/PYI-861)
> PYIC-861: Add passport VC issuer config

- deploy/template.yaml
Set Java tiered compilation level
Mark Sailes released a blog post describing how you can reduce cold
start times by setting the Java tiered compilation level. Setting this
global will make the change to all our passport-back lambdas.
For more details on what this does here's the blog post:
https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
> BAU: Set Java tiered compilation level

- .github/workflows/post-merge.yml
- .github/workflows/pre-merge-checks.yml
**AWS perms PR here: https://github.com/alphagov/di-ipv-config/pull/302**
Run integration tests in Github workflows
We want to run the integration tests as part of our Github workflows. To
do this Github actions will need to talk to DynamoDB in the build
account.
We already have a Github OIDC provider deployed in AWS which we use to
put build artefacts into S3. We can use the same patten to access
DynamoDB. A separate PR has been raised on the config dir to give the
AWS role perms to talk to DynamoDB.
- [PYI-889](https://govukverify.atlassian.net/browse/PYI-889)
> PYIC-889: Run integration tests in Github workflows

- integration-test/src/integration-test/java/uk/gov/di/ipv/cri/passport/integrationtest/DateStorePassportCheckIT.java
- lambdas/authorizationcode/src/test/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/domain/VerifiableCredentialTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/DcsResponse.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/CredentialSubject.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/VerifiableCredential.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/helpers/JwtHelper.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/helpers/JwtHelperTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/DcsCryptographyServiceTest.java
Fixed our JWTClaimSet generation. We were previously generating the claim twice causing fields to be stored twice at 2 different levels within the VC.
Also updated the storage of some of the VC parameters to work. Now that we aren't using the jackson object mapper it highlighet some issues when trying to store either a "LocalDate" or a "UUID" variable type. All of these variables have been updated to be stored as Strings.
To fix the structure of the Passport VC.
> Bau fix passport cri evidence structure

- deploy/template.yaml
- Give issuecredential lambda SQS perms
- Add the SQS queue URL to the lambda as an env var 
Add the perms required for the issuecredential lambda to write to the
audit event SQS queue.
`SQSSendMessagePolicy` gives the message write permissions. We also need
the KMS permissions as the queue is configured to encrypt messages at
rest and SAM doesn't have a policy template that covers this (obviously
required) use case.
This also adds the SQS queue URL to the lambda as an env var so the lib
actually sending the messages know where to send them.
Whilst not strictly in scope for the core team for slice 2, I've added
it to this lambda first as the KBV teams designated slice 2 message is
`KBV_ADDRESS_CREDENTIAL_ISSUED`. So assuming a matching first message
from the Passport CRI, this lambda is …
> PYIC-927: Give issuecredential lambda SQS perms

- deploy/template.yaml
- lambdas/authorizationcode/build.gradle
- lambdas/authorizationcode/src/main/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandler.java
- lambdas/authorizationcode/src/test/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandlerTest.java
- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lib/build.gradle
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditEvent.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditEventTypes.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/error/ErrorResponse.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/exceptions/SqsException.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/AuditService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/AuditServiceTest.java
Add common Audit service that writes audit events onto the passport SQS queue. This will write an event onto the queue to track when we have sent a request to DCS.
This is the same implementation as on ipv-core and will write the messages onto the queue in JSON format.
- [PYI-862](https://govukverify.atlassian.net/browse/PYI-862)
> PYIC-862: Send audit event to the sqs queue for when a request has been sent to DCS

- lambdas/sharedattributes/build.gradle
- lambdas/sharedattributes/src/main/java/uk/gov/di/ipv/cri/passport/sharedattributes/SharedAttributesHandler.java
- lambdas/sharedattributes/src/test/java/uk/gov/di/ipv/cri/passport/sharedattributes/SharedAttributesHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/exceptions/JarValidationException.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/exceptions/SharedAttributesValidationException.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidator.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidatorTest.java
Crated a new validator class to validate the new JAR request from ipv-core. The validator will check the following:
- Validates the client_id is one we have configured within SSM
- Validates the JWT header matches the signing algorithm we have configured for the client
- Validates the JWT signature
- Validates the various JWT claims i.e, correct values for aud, iss, response_type, redirect_uri. Checks the JWT hasn't expired or too far in the future, or is before the nbf claim date.
IPV-Core will now send its authorize request as a JAR. So the "request" JWT that is sent to the SharedAttributes handler now has additional claims that describe ipv-core as the connecting client. We now need to validate those claims and the JWT to ensure the connecting client can be trusted.
- …
> PYIC-946: Validate JAR request from ipv-core

- integration-test/src/integration-test/java/uk/gov/di/ipv/cri/passport/integrationtest/DateStorePassportCheckIT.java
- lambdas/authorizationcode/src/main/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandler.java
- lambdas/authorizationcode/src/main/java/uk/gov/di/ipv/cri/passport/authorizationcode/validation/AuthRequestValidator.java
- lambdas/authorizationcode/src/test/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandlerTest.java
- lambdas/authorizationcode/src/test/java/uk/gov/di/ipv/cri/passport/authorizationcode/validation/AuthRequestValidatorTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/domain/VerifiableCredentialTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/error/ErrorResponse.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/PassportCheckDao.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/DcsPassportCheckServiceTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/PassportServiceTest.java
Update the AuthorizationCodeHandler lambda to accept a new header "user_id" from passport-front. The value in this header is then stored alongside the passport data from DCS and the passport-front values within the DcsResponse DynamoDB table.
The user_id value is stored in the DB to be used later during the IssueCredential lambda where we generate the VC. The VC will need to include this userId value which it will be able to read off the DCSResponse record.
- [PYI-950](https://govukverify.atlassian.net/browse/PYI-950)
> PYIC-950: Store user_id header value in DCSResponse DynamoDB table

- .github/workflows/post-merge.yml
- .github/workflows/pre-merge-checks.yml
- deploy/template.yaml
- integration-test/src/integration-test/java/uk/gov/di/ipv/cri/passport/integrationtest/KmsRsaDecrypterIT.java
- lambdas/jwtauthorizationrequest/src/main/java/uk/gov/di/ipv/cri/passport/jwtauthorizationrequest/JwtAuthorizationRequestHandler.java
- lambdas/jwtauthorizationrequest/src/test/java/uk/gov/di/ipv/cri/passport/jwtauthorizationrequest/JwtAuthorizationRequestHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/KmsRsaDecrypter.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidator.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidatorTest.java
A POC to show that we can decrypt externally encrypted messages with an
RSA key in KMS.
The decrypter uses KMS to decrypt the encrypted key used to actually
encrypt the content of the JWE.
It then delegates to the nimbus ContentCryptoProvider, which the nimbus
provided RSA decrypter uses.
PYIC-962: Add KmsRsaDecrypter to the JarValidator class
Co-authored-by: Chris Wynne [christopher.wynne@digital.cabinet-office.gov.uk](mailto:christopher.wynne@digital.cabinet-office.gov.uk)
Included the new KmsDecrypter into the JarValidator in order to decrypt the JWE and return a SignedJWT.
Added a new env variable to store the SSM param name of the KmsEncryptionKeyId.
We are using KMS to decrypt the JAR's. This sets a custom Decrypter that uses an RSA key from KMS to decrypt the JAR coming from …
> PYIC-962: Create new KMS RSA decrypter and include in the JAR validation

- deploy/template.yaml
Add CloudFormation resources to start sending our lambda application
logs and API gateway access logs to Splunk.
For the API gateway logs I've reused the JSON format we have defined for
the core-front Fargate API gateway logs, for consistency. The only
difference is the addition of responseLatency which could be helpful
when looking at slow lambdas.
For the lambdas I've explicitly declared a log group resource even
though lambda creates one for you. This is because the lambda created
log groups will store messages indefinitely by default. You can change
this by declaring the log group yourself. As long as the name is the
same as the log group lambda creates and writes to, the function should
write to this new log group. It will be interesting to see if these log
groups deploy cleanly, …
> PYIC-1066: Lambda and API gateway logs to Splunk

- integration-test/src/integration-test/java/uk/gov/di/ipv/cri/passport/integrationtest/DateStorePassportCheckIT.java
- lambdas/authorizationcode/src/main/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandler.java
- lambdas/authorizationcode/src/test/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/domain/VerifiableCredentialTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/DcsPayload.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/DcsResponse.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/ContraIndicators.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/CredentialSubject.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/Evidence.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/NameParts.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/Passport.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/VerifiableCredential.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/VerifiableCredentialConstants.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/PassportCheckDao.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/DcsCryptographyService.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/helpers/JwtHelperTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/DcsCryptographyServiceTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/DcsPassportCheckServiceTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/PassportServiceTest.java
Conform to [RFC0024](https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0024-identity-vc-for-checks.md#identity-rfc-0024-verifiable-credentials-for-identity-checks)
[PYIC-1038: Rename PassportAttributes to DcsPayload](https://github.com/alphagov/di-ipv-cri-uk-passport-back/commit/346f07e02e040323d20f5e5e3888c33da3058c9a) 
The PassportAttributes class contained more than just passport
attributes. Things like correlation ID and request IDs are specific to
DCS. This class is better names as DcsPayload.
[PYIC-1038: Return VC that conforms to RFC0024](https://github.com/alphagov/di-ipv-cri-uk-passport-back/commit/170608b6b32667cb041fc50e017b46cd06135d6e) 
Update the VC returned by passport CRI to match the spec defined in
RFC0024: …
> PYIC-1038: Conform to RFC0024

- deploy/template.yaml
This adds a parameter named `ProvisionedConcurrentExecutions` to the CFN
template. When this is set to a value greater than 0 each Passport Back
lambda will be provisioned that number of concurrent executions as a
means to reduce the impact of cold starts. The default value is 0.
This will permit turning on and adjusting provisioned concurrent
executions via CloudFormation update-stack operations.
In order to enable provisioned concurrent executions it is necessary to
also enable and create an alias which has been named 'live'.
To help reduce the impact of cold starts for the MVP.
This follows the same pattern as for core-back which was recently added. We do not have developer environments for passport CRI so it cannot be tested in the same way. The template validates and passes a CFN …
> PYIC-1171 Add Provisioned Capacity Parameter

- integration-test/src/integration-test/java/uk/gov/di/ipv/cri/passport/integrationtest/DateStorePassportCheckIT.java
- lambdas/authorizationcode/src/main/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandler.java
- lambdas/authorizationcode/src/test/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/domain/VerifiableCredentialTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/PassportCheckDao.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/DcsPassportCheckServiceTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/PassportServiceTest.java
Return `aud` claim in VC JWT
The core is now validating the claims set returned to it from a CRI.
This includes checking that the audience claim has the expected value.
This updates passport to return that claim with a value from the clients
configuration.
This is currently piggybacking on the clients issuer value from config.
At the moment these (issuer and audience) are the same with core. But we
need to look more closely at how we are managing these values as our
current approach is quite confusing.
- [PYI-1238](https://govukverify.atlassian.net/browse/PYI-1238)
> PYIC-1238: Return `aud` claim in VC JWT

- deploy/template.yaml
pointed /authorization and /jwt-authorise-request routes to internal api
modified:   deploy/template.yaml
This Creates a new internal api gateway for passport. 
It should redirect the following existing routes:
* Authorisation /authorisation (linked to IPV Passport Authorisation lambda)
* JWT Autorisation request /jwt-authorise-request (linked to IPV Passport JWT Authorisation request)
To the internal api gateway 
We are going to be adding api keys to the api - this should make this easier to do so. 
- [PYIC-1246](https://govukverify.atlassian.net/browse/PYIC-1246)
> PYIC-1246 Created internal api

- deploy/template.yaml
all environments should have been switched to the new internal api gateway
so the legacy call to the external should no longer be required.
removed events to external api for the internal api routes. 
all environments should have been switched to the new internal api gateway
so the legacy call to the external should no longer be required.
- [PYIC-1246](https://govukverify.atlassian.net/browse/PYIC-1246)
> PYIC-1246 Removed the duplicated events

- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/helpers/KmsSigner.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/helpers/KmsSignerTest.java
Fix KMS signature padding issue
Use nimbus's Base64URL.encode() function to base64URL encode the
signature bytes received from KMS.
The encoder offered by java.util via `Base64.getUrlEncoder()` does not
strip padding as we expected. It's java docs reference Table 2 of RFC
4648, which is a bit vague about the handling of padding (the "previous one"
the quote mentions is regular old base 64):
"This encoding is technically identical to the previous one, except
for the 62:nd and 63:rd alphabet character, as indicated in Table 2."
As a result we were occasionally including an `=` on the end of our
serialized JWT strings. The nimbus lib is gracious enough to handle
these and still verify the signatures correctly, but it was causing
issues in SPOT. So here's a fix.
> BAU: Fix KMS signature padding issue

- build.gradle
- integration-test/build.gradle
- lambdas/accesstoken/build.gradle
- lambdas/authorizationcode/build.gradle
- lambdas/issuecredential/build.gradle
- lambdas/jwtauthorizationrequest/build.gradle
- lambdas/stubdcs/build.gradle
- lib/build.gradle
Define common versions for libs
We were using different versions of the same libs in different lambdas.
This defines a structure in the root project where we can define the
versions we want to use and then pull them in in the sub projects.
This makes it easy to bump all versions in case of a security issue, as
well as ensuring consistency to help diagnose weird bugs.
This also sorts all the dependencies to scratch an itch.
> BAU: Define common versions for libs

- lambdas/jwtauthorizationrequest/build.gradle
- lambdas/jwtauthorizationrequest/src/main/java/uk/gov/di/ipv/cri/passport/jwtauthorizationrequest/JwtAuthorizationRequestHandler.java
- lambdas/jwtauthorizationrequest/src/test/java/uk/gov/di/ipv/cri/passport/jwtauthorizationrequest/JwtAuthorizationRequestHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/error/RedirectErrorResponse.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/exceptions/RecoverableJarValidationException.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidator.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidatorTest.java
For 'recoverable' JAR validation errors return the redirect_uri alongside the oauth error, in the shape:
```
{
"redirect_uri": "http://example.com",
"oauth_error": {
"error": "server_error",
"error_description": "Description of the oauth error"
}
}
```
The error is considered recoverable as long as:
- client_id is valid
- redirect_uri is valid
- JAR decryption is valid
- JAR signature is valid
If a JAR validation error occurs and is 'recoverable' we want to redirect the user back to core rather than ending the journey
- [PYIC-1326](https://govukverify.atlassian.net/browse/PYIC-1326)
> PYIC-1326 Update JwtAuthorizationRequest lambda to handle recoverable error scenario

- deploy/template.yaml
- lambdas/authorizationcode/src/main/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandler.java
- lambdas/authorizationcode/src/test/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lambdas/jwtauthorizationrequest/build.gradle
- lambdas/jwtauthorizationrequest/src/main/java/uk/gov/di/ipv/cri/passport/jwtauthorizationrequest/JwtAuthorizationRequestHandler.java
- lambdas/jwtauthorizationrequest/src/test/java/uk/gov/di/ipv/cri/passport/jwtauthorizationrequest/JwtAuthorizationRequestHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditEventTypes.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/AuditServiceTest.java
Added audit events:
IPV_PASSPORT_CRI_START
IPV_PASSPORT_CRI_RESPONSE_RECEIVED
IPV_PASSPORT_CRI_REQUEST_SENT
IPV_PASSPORT_CRI_END
IPV_PASSPORT_CRI_VC_ISSUED
So we are sending the agreed events to the audit system
- [PYIC-1088](https://govukverify.atlassian.net/browse/PYIC-1088)
> PYIC-1088 Add audit events

- .github/workflows/post-merge.yml
- .github/workflows/pre-merge-checks.yml
- deploy/template.yaml
- integration-test/src/integration-test/java/uk/gov/di/ipv/cri/passport/integrationtest/DateStorePassportCheckIT.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/DataStore.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/AccessTokenItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/AuthorizationCodeItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/DynamodbItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/PassportCheckDao.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/AccessTokenService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/AuthorizationCodeService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/DcsPassportCheckService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/PassportService.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/persistance/DataStoreTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationServiceTest.java
Enabled the ttl setting on the DynamoDB tables.
Set the ttl property on each of the DynamoDB items based off a SSM param value. The value is recored as an epoch seconds value
To ensure data is not retained for longer than necessary, the ttl value will be used by DynamoDB to automatically delete records after they have expired.
- [PYI-1381](https://govukverify.atlassian.net/browse/PYI-1381)
> PYIC-1381: Add ttl value to passport dynamoDB items

- integration-test/src/integration-test/java/uk/gov/di/ipv/cri/passport/integrationtest/KmsRsaDecrypterIT.java
- lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandler.java
- lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/validation/TokenRequestValidator.java
- lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandlerTest.java
- lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/validation/TokenRequestValidatorTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidator.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidatorTest.java
Remove token auth method configuration
Our OAuth spec states that a CRI should enforce the private_key_jwt
client authentication method. We currently have the ability to bypass
this with some config for client. We're using private keys for auth in
all envs and are well practiced at it. The configuration was originally
added to help us build out this feature. As we don't really need this
functionality anymore we should remove this potential foot cannon.
- [PYI-1393](https://govukverify.atlassian.net/browse/PYI-1393)
> PYCI-1393: Remove token auth method configuration

- deploy/template.yaml
Add new condition to toggle whether we need logging subscription filters depending on environment. For the development environment we don't need these subscription filters.
Remove the subscription filters for the development environment
- [PYI-1421](https://govukverify.atlassian.net/browse/PYI-1421)
> PYIC-1421: Add condition for the logging subscription filters to not use them on the dev environment

- deploy/template.yaml
- lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandler.java
- lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/AuthorizationCodeItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/AuthorizationCodeService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/AuthorizationCodeServiceTest.java
Expire auth codes after a short period 
We want to expire auth codes after a configured period of time. RFC 6749
states that they should have a short life span. 10 minutes is
recommended.
- [PYI-1447](https://govukverify.atlassian.net/browse/PYI-1447)
> PYIC-1447: Expire auth codes after a short period

- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidator.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidatorTest.java
Throw SsmException instead of ParameterNotFoundException
We validate the client ID received in the auth request params by trying
to fetch some arbitrary config for that client from the param store. If
we are able to we consider the client ID validated.
If we don't have any configuration for that client ID the powertools lib
will throw. We were expecting to catch a ParameterNotFound exception,
however that's not what we get. Instead we get a SsmException due to the
lambda not having permissions to get that parameter (even though it
doesn't exist).
ParameterNotFoundException actually extends SsmException, so if for some
reason the lambda DID have perms and threw that specific exception we'd
still catch it here.
> BAU: Throw SsmException instead of ParameterNotFoundException

- build.gradle
- lambdas/accesstoken/build.gradle
- lambdas/accesstoken/src/main/resources/log4j2.yaml
- lambdas/authorizationcode/build.gradle
- lambdas/authorizationcode/src/main/resources/log4j2.yaml
- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/resources/log4j2.yaml
- lambdas/jwtauthorizationrequest/build.gradle
- lambdas/jwtauthorizationrequest/src/main/resources/log4j2.yaml
- lib/build.gradle
Log in JSON format
This leverages the AWS docs found here:
https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html#java-logging-log4j2
as well as RFC0030:
https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0030-cross-programme-logging-format.md
and the auth teams previous good work:
https://github.com/alphagov/di-authentication-api/blob/main/ipv-api/src/main/resources/log4j2.xml
This uses the aws-lambda-java-log4j2 library to allow is to include
the AWS request ID in each log line.
It defines a couple of new gradle configurations in the root project
which are then pulled in by the sub projects to reduce repetition.
It adds a YAML configuration file to each sub project to configure the
logging. Currently we're only adding a couple of custom fields,
session-id …
> PYIC-1487: Log in JSON format

- lambdas/jwtauthorizationrequest/src/main/java/uk/gov/di/ipv/cri/passport/jwtauthorizationrequest/JwtAuthorizationRequestHandler.java
- lambdas/jwtauthorizationrequest/src/test/java/uk/gov/di/ipv/cri/passport/jwtauthorizationrequest/JwtAuthorizationRequestHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/error/RedirectErrorResponse.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/exceptions/RecoverableJarValidationException.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidator.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/validation/JarValidatorTest.java
When it is present and parsable in the request, include the `state` param in the JwtAuthorizationRequest recoverable error response:
```
{
redirect_uri: 'redirect.com',
state: 'xyz',
oauth_error: {
error: 'invalid_request',
error_description: 'something went wrong'
}
}
```
We omit it from the response if it's not present in the request
RFC6749 (https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1) requires the state param to be included in the redirect uri query alongside the error params (if it is provided in the original client authorization request). We pass it back to the frontend here so it can set it in the redirect url.
- [PYIC-1449](https://govukverify.atlassian.net/browse/PYIC-1449)
> PYIC-1449 Include state param in recoverable error response

- deploy/template.yaml
This sets the provisioned concurrency of each lambda based using a look
up in the Mappings section. This makes it simpler to find the setting
and to deploy changes.
As above
As above
The initial implementation relied upon setting the parameter via the cli or CI configuration. Having the setting within the CI configuration makes it harder to find and also creates "interesting" scenarios where updates to the CI configuration do not necessarily trigger a deployment of the app that propagates through environments. Moving the setting into the template's Mappings section makes it simpler to find and will always trigger a deployment when it changes.
This has been successfully deployed into my dev environment. Integration and Production are currently set to provisioned concurrency of 1 and this …
> PYIC-1495 Set Provisioned Concurrency Within Template

- build.gradle
Fix JSON logging
The logging was broken with the move to using log4j2 for logging in JSON
format. This was due to a missing dependency that allows parsing of YAML
files. log4j2 was failing to parse the YAML configuration file and
falling back to its default configuration. The default config only logs
warn and above.
The general approach to logging my change fairly soon, but we should fix this
up in the mean time none the less.
> BAU: Fix JSON logging

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/AccessTokenItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/AccessTokenService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/AccessTokenServiceTest.java
Store access token expiry time on dynamodb record so we can check it on issuing credential. Throw access denied error if access token has expired.
[RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-7) states that the resource server must validate any access token to ensure it hasn't expired. We weren't checking this previously.
- [PYIC-1462](https://govukverify.atlassian.net/browse/PYIC-1462)
> PYIC-1462 Validate access token expiry

- deploy/template.yaml
- lambdas/authorizationcode/src/main/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandler.java
- lambdas/authorizationcode/src/test/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditEvent.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditEventUser.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditExtensions.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditExtensionsVcEvidence.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditRestricted.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditRestrictedVcCredentialSubject.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/AuditService.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/AuditServiceTest.java
Add details of the request sent to DCS in the IPV_PASSPORT_CRI_REQUEST_SENT. This is in the same format as VC `credential_subject` field.
Also add VC details to the IPV_PASSPORT_CRI_VC_ISSUED audit event.
This is a minimal implementation to meet our deadline and should be revised with additional testing and code refactoring.
We need to log this information for fraud detection purposes.
- [PYI-1514](https://govukverify.atlassian.net/browse/PYI-1514)
> PYIC-1514: Add Passport PII to REQUEST_SENT audit event

- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/AccessTokenItem.java
Give AccessTokenItem default constructor
DynamodDb BeanTableSchema needs a default constructor. A specific
constructor was defined which meant the default no longer existed. This
puts it back.
Have tested by deploying to the dev account and all good.
> BAU: Give AccessTokenItem default constructor

- lambdas/accesstoken/build.gradle
- lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandler.java
- lambdas/authorizationcode/build.gradle
- lambdas/authorizationcode/src/main/java/uk/gov/di/ipv/cri/passport/authorizationcode/AuthorizationCodeHandler.java
- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/jwtauthorizationrequest/build.gradle
- lambdas/jwtauthorizationrequest/src/main/java/uk/gov/di/ipv/cri/passport/jwtauthorizationrequest/JwtAuthorizationRequestHandler.java
Set `@Logging` annotation and add jackson yaml
This brings in a couple of fixes for the logging in passport.
The previous fix of adding the jackson-dataformat-yaml lib to allow
parsing of the log4j2 config file was undone when I added powertools.
It's still needed so it's being reintroduced.
Secondly, I completely forget to add the quite important `@Logging`
annotation to our handlers. 🤦🏻‍♂️
> BAU: Set `@Logging` annotation and add jackson yaml

- lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/helpers/LogHelper.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/helpers/RequestHelper.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/AccessTokenService.java
Update log field names
Make the log field names camel case to be consistent with what we log in
core. This also changes the session_id field to passportSessionId. This
is to help to differentiate it from other session IDs we may end up
logging, such as persistent session ID. It's also consistent with what
we're logging in core. This will also get logged in the passport front
so we can tie frontend and backend logs together.
> BAU: Update log field names

- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/error/ErrorResponse.java
Revoke the access token after it has been used to retrieve a credential
To avoid any possible re-use of access tokens.
- [PYI-1468](https://govukverify.atlassian.net/browse/PYI-1468)
> PYIC-1468: revoke access tokens after use

- lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandler.java
- lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandlerTest.java
Return correct error code if redirect URLs don't match
If the redirect URL received at the token endpoint doesn't match that
received on the auth endpoint we should return invalid_grant, according
to the OAuth spec.
- [PYI-1529](https://govukverify.atlassian.net/browse/PYI-1529)
> PYIC-1529: Return correct error code if redirect URLs don't match

- .github/workflows/checkov.yml
Install setuptools before attempting to install checkov.
It seems that checkov has recently updated to 2.1.34 and now requires `setuptools` installed before it can be installed. This PR fixes the install but checkov check itself fails because it has new rules which were not previously met. They will be addressed in a separate PR.
> BAU Fix installation of Checkov

- deploy/template.yaml
- CKW_AWS_117: We have future work to move the lambdas into our own VPC for greater
egress controls but for now we are ok with them being in an AWS
managed VPC
- CKW_AWS_115: Each account has an allocation of 1000 concurrent lambda
executions per region. We do not have enough data to make informed
decisions how this allocation might be best set on a per function
basis. For now it makes sense to permit each function to draw on the
allocations as they need it.
As above
As above.
Version `2.1.34` of checkov introduced some new rules.
> BAU Address new Checkov Rules

- deploy/template.yaml
- lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandler.java
- lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/validation/TokenRequestValidator.java
- lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandlerTest.java
- lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/validation/TokenRequestValidatorTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/helpers/LogHelper.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/persistence/item/ClientAuthJwtIdItem.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ClientAuthJwtIdService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationService.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/ClientAuthJwtIdServiceTest.java
Validate the JWT id (JTI) of the access token private key JWT request
- check that it is present in the JWT claims
- check that it is unique ie. has not already been used before, by storing previously used JWT ids
OpenID Connect Core 1.0 Section 9 ([Final: OpenID Connect Core 1.0 incorporating errata set 1](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication)) states that the private_key_jwt is required to contain a jti claim, which is a unique identifier for the JWT. It should be used to prevent re-use of the tokens, which MUST only be used once
- [PYIC-1450](https://govukverify.atlassian.net/browse/PYIC-1450)
> PYIC-1450 Validate JTI of access token private key JWT request

- lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandlerTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/AccessTokenServiceTest.java
Ensure we can create access tokens with null resource ID
When performing the token exchange the authcode table has an entry for
the dcs response resource id. Later changes will mean that this value
will be blank. Ensure that the code can accommodate the value being
blank, creating a token entry with a blank dcs resource id entry in that
case.
This adds a test that shows there is no issue with the value being
persisted being null
- [PYI-1556](https://govukverify.atlassian.net/browse/PYI-1556)
> PYIC-1556: Ensure we can create access tokens with null resource ID

- lambdas/initialisesession/src/main/java/uk/gov/di/ipv/cri/passport/initialisesession/InitialiseSessionHandler.java
- lambdas/initialisesession/src/test/java/uk/gov/di/ipv/cri/passport/initialisesession/InitialiseSessionHandlerTest.java
Do not expect to receive session ID in initialisesession λ
We were previously passing in the frontend's session ID in a header to
the jwt auth λ. Now that we're generating the session ID in the back we
don't need to do this and shouldn't throw if it's not there.
> BAU: Do not expect to receive session ID in initialisesession λ

- deploy/template.yaml
- lambdas/buildclientoauthresponse/build.gradle
- lambdas/buildclientoauthresponse/src/main/java/uk/gov/di/ipv/cri/passport/buildclientoauthresponse/BuildClientOauthResponseHandler.java
- lambdas/buildclientoauthresponse/src/main/resources/log4j2.yaml
- settings.gradle
Create new empty gradle module for the new "build-client-oauth-response" lambda.
This is the start of a new lambda that will be responsible for generating an Oauth response back to core, i.e generating an auth code and all the params needed to redirect back to core-front.
A further PR will be added to add the necessary AWS SAM config to start deploying this new lambda
- [PYI-1551](https://govukverify.atlassian.net/browse/PYI-1551)
> PYIC-1551: Create blank lambda code for the build-client-oauth-response lambda

- deploy/template.yaml
Fix for Check Passport Function: `ipv-passport-authorization-build already exists in stack`
> FIX: ipv-passport-authorization-build already exists in stack.

- deploy/template.yaml
The `AWS::Serverless::Function` will create a log group if one does not
exist with the expected log group name. We define our log groups in the
template rather than relying on the serverless transform because we want
to set the retention period. The initial PR introduced two new functions
and their log groups, the log group definition referenced the function
which meant the function would be created first, causing a "log group
with the same name exists" error when eventually CFN came to create the
log group resource. This change adds a depends on between the function
and the log group so the log group should be created first.
As above
As above
This has been tested in passport development A environment with @dannyhayes-gds 
As above.
- …
> PYIC-1594 Fix Deployment of New Lambdas

- deploy/template.yaml
Passport back stack is failing to deploy into the staging environment
whilst timing out attempting to add the provisioned concurrency to the
new version before re-weighting the alias to the new version; it also
times out when trying to roll back. This change temporarily removed
provisioned concurrency to see if the stack will successfully deploy. We
can then work to reinstate it.
As above
As above
In an attempt to recover the passport-back stack in staging to a working deployment. Production is changed to remain consistent with staging.
- [PYI-1594](https://govukverify.atlassian.net/browse/PYI-1594)
> PYIC-1594 Remove Provisioned Concurrency

- deploy/template.yaml
Turn provisioned concurrency back on for staging & production environments
This was turned off previously as an attempt to fix the provisioned concurrency issue we saw
> Turn provisioned concurrency back on

- deploy/template.yaml
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/CheckPassportHandler.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/CheckPassportHandlerTest.java
Stop generating an auth code in the passport check lambda and only return a "retry"/"finish" response.
Remove unnecessary DynamoDB permission to the auth code table and extra env var that is no longer needed.
The auth code is now generated in a different lambda so this auth code is not being used.
- [PYI-1606](https://govukverify.atlassian.net/browse/PYI-1606)
> PYIC-1606: Stop generating auth code in passport check lambda

- deploy/template.yaml
Whilst an engineer was fixing the failed deployment of the passport back
stack in staging they removed the log groups. Although those log groups
have been manually put back the log group subscription filters are still
missing. CFN will not recreate them unless we:
1. Remove the resources from the stack so that the stack's view matches
reality
2. Then add the resources back in so that CFN will recreate them.
This introduces a temporary condition to remove the missing log group
subscription filters for the Staging environment. Once deployed we will
then remove this change and CFN will recreate them.
As above.
As above.
The following resources have bene deleted manually and we need to put them back. Until this happens logs for these resources will not be sent to Splunk. I would prefer we …
> BAU Fix Drift In Staging Environment

- deploy/template.yaml
This reverts commit f6dfdb4aa99a983929672ad32c7671713994e003.
The above commit was made to address the stack drift for passport back in
the staging environment. That commit has been deployed so reverting it
will make CFN recreate the missing log group subscription filters.
As above
As above
Please see: https://github.com/alphagov/di-ipv-cri-uk-passport-back/pull/204
The above PR has been deployed through all environments:
https://cd.gds-reliability.engineering/teams/di-ipv/pipelines/cri-passport-deploy-to-production/jobs/deploy-passport-back/builds/53
There is no drift on the stack caused by `DELETED` resources
```
GDS11321:logGroups dan.worth$ aws-vault exec passport-staging-admin -- aws cloudformation describe-stack-resource-drifts --stack-name ipv-passport-back-staging | jq …
```
> Revert "BAU Fix Drift In Staging Environment"

- lambdas/initialisesession/src/main/java/uk/gov/di/ipv/cri/passport/initialisesession/InitialiseSessionHandler.java
- lambdas/initialisesession/src/test/java/uk/gov/di/ipv/cri/passport/initialisesession/InitialiseSessionHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/JarResponse.java
Stop returning the oauth params from the initialise session lambda.
These params are now stored in the back-end session so they don't need to be passed back to the front-end. The params will just be loaded from the back-end session DynamoDB and be used when needed.
- [PYI-1609](https://govukverify.atlassian.net/browse/PYI-1609)
> PYIC-1609: Stop sending the oauth params back from the initialise session lambda

- lambdas/buildclientoauthresponse/build.gradle
- lambdas/buildclientoauthresponse/src/main/java/uk/gov/di/ipv/cri/passport/buildclientoauthresponse/BuildClientOauthResponseHandler.java
- lambdas/buildclientoauthresponse/src/test/java/uk/gov/di/ipv/cri/passport/buildclientoauthresponse/BuildClientOauthResponseHandlerTest.java
If no passport details attempt has been made (attemptCount = 0) return an AccessDenied response
So we can handle the new 'escape route' on passport front if the user leaves the journey to prove their identity another way
- [PYIC-1638](https://govukverify.atlassian.net/browse/PYIC-1638)
> PYIC-1638 Update Passport CRI Backend to handle escape route

- build.gradle
- lambdas/buildclientoauthresponse/src/main/java/uk/gov/di/ipv/cri/passport/buildclientoauthresponse/BuildClientOauthResponseHandler.java
- lambdas/buildclientoauthresponse/src/test/java/uk/gov/di/ipv/cri/passport/buildclientoauthresponse/BuildClientOauthResponseHandlerTest.java
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/CheckPassportHandler.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/CheckPassportHandlerTest.java
- lambdas/initialisesession/src/main/java/uk/gov/di/ipv/cri/passport/initialisesession/InitialiseSessionHandler.java
- lambdas/initialisesession/src/test/java/uk/gov/di/ipv/cri/passport/initialisesession/InitialiseSessionHandlerTest.java
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lib/build.gradle
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditEvent.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/auditing/AuditEventUser.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/AuditService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/PassportSessionService.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/AuditServiceTest.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/PassportSessionServiceTest.java
- lombok.config
Move govuk_signin_journey_id into audit event users
We were logging the govuk journey ID at the top level of the Audit
Events. They need to be nested in the user sub object.
- [PYI-1791](https://govukverify.atlassian.net/browse/PYI-1791)
> PYIC-1791: Move govuk_signin_journey_id into audit event users

- .github/workflows/secure-post-merge.yml
PYIC-1715 seperated out aws roles for integration tests vs pipeline deployment
PYIC-1715 seperated out aws roles for integration tests vs pipeline deployment
> PYIC-1715 seperated out aws roles for integration tests vs pipeline deployment

- infrastructure/lambda/template.yaml
Renamed GatewayId export names.
Aligning with expected names in deployed support stacks.
> LIME-131 Rename GatewayId exports to match dns and front.

- infrastructure/lambda/template.yaml
Disable use of core-infrastructure keys.
core-infrastructure stack is currently not on the environment.
Reverting to use existing keys.
> LIME-131 Disable use of core-infrastructure keys.

- infrastructure/lambda/template.yaml
Disable LinkUsagePlanApiKey1 export
Key was disabled in the previous commit.
> LIME-131 Disable LinkUsagePlanApiKey1 export

- .github/workflows/pre-merge-checks.yml
Disable Integration tests.
The stack being deployed is the expected stack for the tests.
Disabling test until it is deployed.
> LIME-131 Disable Integration tests until stack for the test is deployed.

- .github/workflows/pre-merge-checks.yml
- .github/workflows/secure-post-merge.yml
Disable Integration tests (post-merge)
The stack being deployed is the expected stack for the tests.
Disabling test until it is deployed.
> LIME-131 Disable Integration tests (post merge)

- deploy/template.yaml
Disabled api-gateway log groups
Pipeline is failing on re-creation of log-groups. 
> LIME-131 Disable api-gateway log groups to overcome re-deployment issue

- deploy/template.yaml
Keep the old subscription filters as the current name and add CSLS to the name of the new one.
A resource limit error is triggered when deploying the stack and is believed due to there temporarily being 3 during deployment and going over the limit of 2 sub filters per log group. 
- [LIME-192](https://govukverify.atlassian.net/browse/LIME-192)
> LIME-192 Keep current names for old subscription filter and add CSLS to new

- deploy/template.yaml
Switched to the same naming as what's currently in main to prevent the Service Limit Exception caused by CF trying to create more than two logGroup Subscriptions per group.
> LIME-192 Switched the filter logs back to become deployable

- deploy/template.yaml
Removed old prod log subscription
Because the old endpoint is being decommissioned
> Removing-CSLS-Rust: Removing old CSLS endpoint

- deploy/template.yaml
Adding alerts for the passport CRI API
Added alerts
Added config to send alerts to pager duty
To enable passport to alert slack when it is having issues
> LIME-209: Adding alerts for passport api errors

- build.gradle
- deploy/template.yaml
- lambdas/accesstoken/build.gradle
- lambdas/accesstoken/src/main/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandler.java
- lambdas/accesstoken/src/test/java/uk/gov/di/ipv/cri/passport/accesstoken/AccessTokenHandlerTest.java
- lambdas/buildclientoauthresponse/build.gradle
- lambdas/buildclientoauthresponse/src/main/java/uk/gov/di/ipv/cri/passport/buildclientoauthresponse/BuildClientOauthResponseHandler.java
- lambdas/buildclientoauthresponse/src/test/java/uk/gov/di/ipv/cri/passport/buildclientoauthresponse/BuildClientOauthResponseHandlerTest.java
- lambdas/checkpassport/build.gradle
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/CheckPassportHandler.java
- lambdas/checkpassport/src/test/java/uk/gov/di/ipv/cri/passport/checkpassport/CheckPassportHandlerTest.java
- lambdas/initialisesession/build.gradle
- lambdas/initialisesession/src/main/java/uk/gov/di/ipv/cri/passport/initialisesession/InitialiseSessionHandler.java
- lambdas/initialisesession/src/test/java/uk/gov/di/ipv/cri/passport/initialisesession/InitialiseSessionHandlerTest.java
- lambdas/issuecredential/build.gradle
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lib/build.gradle
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/metrics/Definitions.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/service/PassportService.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/PassportServiceTest.java
Add AWS Lambda Powertools to Template - namespace/service follows naming conventions used in the other CRIs
Added powertools metrics to aspect section of gradle builds.
Moved existing powertools to aspects section.
Added the following metrics to PassportCRI
All Lambdas - Lambda Completed ok/error
Check Passport Lambda
PermitCheckStatus - Verified, Retry, Unverified
FormDataParse - pass/fail
DCS Check Request - succeeded/failed
DCS Response Type - ok/error/empty
IssueCredential Lambda
Passport Contra Indicators - generated
Metrics added to cover metrics requested for LIME-189
Definitions located in passport lib ...passport/library/metrics/Definitions.java.
- [LIME-189](https://govukverify.atlassian.net/browse/LIME-189)
> LIME-189 Capture PassportCRI Metrics

- deploy/template.yaml
- lambdas/issuecredential/src/main/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandler.java
- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/IssueCredentialHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/ConfigurationService.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/ConfigurationVariable.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/service/ConfigurationServiceTest.java
Using some common CRI code to add VC expiry params to the passport CRI and update passport expiry to 6 months in non prod envs
To allow IPV core to perform identity reuse
> LIME-243: Updating VC expiry to 6 months

- deploy/template.yaml
Added slash to the front of the parameter declaration
Name of the parameter. If the name contains a path (e.g., any forward slashes (/)), it must be fully qualified with a leading forward slash (/). For additional requirements and constraints, see the [AWS SSM User Guide](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-parameter-name-constraints.html).
> LIME-243: Fixed yaml formatting issues

- lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/passport/issuecredential/domain/VerifiableCredentialTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/Passport.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/verifiablecredential/VerifiableCredential.java
- lib/src/test/java/uk/gov/di/ipv/cri/passport/library/helpers/JwtHelperTest.java
Added icaoIssuerCode to passport Verifiable credential
As per VC spec listed here - https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0024-identity-vc-for-checks.md#document-validity-check
> LIME-255 - Updating VC to include issuer code

- lambdas/initialisesession/src/main/java/uk/gov/di/ipv/cri/passport/initialisesession/InitialiseSessionHandler.java
- lambdas/initialisesession/src/test/java/uk/gov/di/ipv/cri/passport/initialisesession/InitialiseSessionHandlerTest.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/domain/JarResponse.java
- New `redirect_uri` parameter added to object  passed from BE to FE
- FE was not provided with `redirect_uri` parameter from BE.
See: https://github.com/alphagov/di-ipv-cri-uk-passport-front/pull/441
- [LIME-399](https://govukverify.atlassian.net/browse/LIME-399)
[LIME-399]: https://govukverify.atlassian.net/browse/LIME-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-399 - Redirect URI fix for associated FE changes.

- .github/workflows/pre-merge-checks.yml
Pinned gradle version 7.6
Codebase supports gradle version 7.6
> LIME-529 - Pinned gradle version 7.6

- deploy/template.yaml
Enabled VC expiry removal in production
So that IPV core and spot can more freely control expirys of VCs
> LIME-567: Enabling VC expiry removal in prod

- deploy/template.yaml
Adjusted thresholds on lambda deviations
To avoid false alarms on period of low traffic
> LIME-384: Increasing alarm threshold to avoid false alarms during periods of low traffic

- .github/workflows/secure-post-merge.yml
Moved test image push above sam deploy
To ensure test image was in place before the pipeline started
> LIME-603: Fixed bug that allowed deployment before the test image had been pushed

- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/pages/PagesFromIpvCoreRepo/EnterPassportDetailsPage.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/CommonSteps.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/stepDefsFromIpvRepo/LoginSteps.java
- acceptance-tests/src/test/java/uk/gov/di/ipv/cri/passport/acceptance_tests/step_definitions/stepDefsFromIpvRepo/PassportCriSteps.java
- acceptance-tests/src/test/resources/features/passport/TestsFromIpvCoreRepo/PassportCRITests.feature
- acceptance-tests/src/test/resources/features/passport/TestsFromIpvCoreRepo/Weleshtranslation.feature
- acceptance-tests/src/test/resources/features/passport/TestsFromIpvCoreRepo/passportCRIStub.feature
Added code to close the driver after each test
Added code to ensure cookies are added to the correct domain
Added code to ensure pages are loaded before checks are performed
So that the passport staging tests pass more reliably
> LIME-603: Fixed failing passport staging tests

- deploy/template.yaml
- lambdas/checkpassport/src/main/java/uk/gov/di/ipv/cri/passport/checkpassport/CheckPassportHandler.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/config/ConfigurationVariable.java
- lib/src/main/java/uk/gov/di/ipv/cri/passport/library/helpers/HttpClientSetUp.java
Added feature toggle for performance testing
Added logging to work around issue of different certificates across environments. Manual steps required for now
To enable performance testing the passport CRI
> LIME-697: Added functionality to allow performance testing

- .github/workflows/secure-post-merge.yml
Fixed failing github action
deploy to build was attempting to pull from an invalid cache object
> LIME-697: Fixing broken github action

- deploy/template.yaml
Added provisioned concurrency to build
To enable performance testing
> LIME-698: Added provisioned concurrency to build for perf testing

- deploy/template.yaml
- lambdas/captureAuditEvents/build.gradle
- lambdas/captureAuditEvents/src/main/java/uk/gov/di/ipv/cri/passport/initialisesession/CaptureAuditEventsHandler.java
- lambdas/captureAuditEvents/src/main/resources/log4j2.yaml
- settings.gradle
Added new capture audit events lambda
Updated template to allow new lambda to read from the audit queue
Limited new lambda to dev and build
To allow performance testing without overloading the TxMA service
> LIME-706: Adding basic lambda to capture TxMA events in dev and build

- deploy/template.yaml
Added function event source mapping
So that the new lambda is triggered on audit queue writes
> LIME-706: added missing event mapping to trigger audit lambda as required

- deploy/template.yaml
Fixed memory size for new lambda
> LIME-706: Updated memory for lambda audit consumer
